/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n7.1.1-55-gca5c0a959d"
#endif /* AVUTIL_FFVERSION_H */
